name: Microservices CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build API Gateway
        run: mvn clean install -DskipTests
        working-directory: api-gateway

      - name: Build Auth Service
        run: mvn clean install -DskipTests
        working-directory: auth-service

      - name: Build Product Service
        run: mvn clean install -DskipTests
        working-directory: product-service
